### ISSUE TITLE
Ordering of sections

### ISSUE THREAD

**Issue by KevinMayfield** [nhsconnect/careconnect-document-viewer#5]
The default position adopted appears to be an ordering of sections in alphabetical order.  Patient Demographics would always need to appear at the top of the rendering for all four ToC use cases.

Likewise, it would be sensible to have the “Person completing record” section along with the “Distribution List” always at the end of the rendering.

If an ordering approach was designed from scratch, there would be a heading configuration file associated with each message type and the end user could use this default configuration file. Otherwise they could have ability to alter the configuration file so they can choose the order of the headings that are most appropriate to themselves.

If changes are made here, without a configuration file approach, the messages should be rendered in a fashion as close to PRSB guidance as possible.

**Comment by KevinMayfield** [comment]
This is not a fault with the renderer. 

The ordering within the sections is done within the FHIR Document, the render can not safely reorder as the document at it is a clinical document and reordering sections may result clinical safety issues. 

If PRSB has now mandated reordering, then the examples need to be re-authored.

**Comment by DrMPM** [comment]
I think the sender would struggle to identify what these safety issues are.  I think there is considerable merit in the user at the GP Practice having the flexibility to present the section order in a manner that best suits their working.   Can you confirm that the default position is to order sections as they appear in the composition profile?

**Comment by KevinMayfield** [comment]
As far as I'm aware the sender can order the document in any order, the profiles dont dictate an order. I would suggest this should be done to make the document more readable and logical. 
The issue is when the document has been sent, the sections shouldn't be recorded as this can change the meaning and context of the document.
I am only referring to the text sections of the document (paragraphs of the letter), so the structured parts (observations, encounters, etc) can be displayed as desired.
